---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scratchpad-pr
spec:
  params:
    - name: repo_url
    - name: revision
  workspaces:
  - name: source
  tasks:
    - name: fetch
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
      workspaces:
      - name: output
        workspace: source
